import { Product, Category } from "./types";

export const CATEGORIES: Category[] = ["All", "Electronics", "Clothing", "Home", "Sports", "Beauty"];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    price: 79.99,
    originalPrice: 129.99,
    image: "https://m.media-amazon.com/images/I/51ZR4lyxBHL.jpg",
    rating: 4.8,
    reviewCount: 2341,
    category: "Electronics",
    badge: "sale",
    description: "Premium sound with 30-hour battery life and active noise cancellation.",
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    price: 149.00,
    image: "https://www.peugeotwatches.com/cdn/shop/products/2059G-FV.jpg?v=1633106380&width=1500",
    rating: 4.7,
    reviewCount: 876,
    category: "Clothing",
    badge: "featured",
    description: "Slim profile with genuine leather strap and sapphire crystal glass.",
  },
  {
    id: 3,
    name: "Smart Home Speaker",
    price: 59.99,
    originalPrice: 89.99,
    image: "https://i.pcmag.com/imagery/roundups/017S1tRIBIkr8Mfan0lnX4J-59..v1657221180.jpg",
    rating: 4.5,
    reviewCount: 1543,
    category: "Electronics",
    badge: "sale",
    description: "Voice-controlled speaker with 360° sound and smart home integration.",
  },
  {
    id: 4,
    name: "Organic Cotton Hoodie",
    price: 64.99,
    image: "https://live.royalapparel.net/prodimg/hires/21052ORGEVG_081423145018.png",
    rating: 4.6,
    reviewCount: 432,
    category: "Clothing",
    badge: "new",
    description: "Sustainably sourced organic cotton in a relaxed, cozy fit.",
  },
  {
    id: 5,
    name: "Ceramic Pour-Over Coffee Set",
    price: 44.99,
    originalPrice: 59.99,
    image: "https://m.media-amazon.com/images/I/7159+ELcEOL._AC_UF894,1000_QL80_.jpg",
    rating: 4.9,
    reviewCount: 654,
    category: "Home",
    badge: "featured",
    description: "Hand-crafted ceramic dripper with matching carafe for the perfect brew.",
  },
  {
    id: 6,
    name: "Yoga Mat Pro",
    price: 38.00,
    image: "https://www.manduka.com/cdn/shop/files/111011050-Mats-PRO71-BLACK-SAGE-01.jpg?v=1768944270&width=871",
    rating: 4.7,
    reviewCount: 1120,
    category: "Sports",
    badge: "new",
    description: "Non-slip, eco-friendly TPE mat with alignment lines and carry strap.",
  },
  {
    id: 7,
    name: "Vitamin C Glow Serum",
    price: 34.99,
    originalPrice: 49.99,
    image: "https://m.media-amazon.com/images/I/51WIfa6crgL.jpg",
    rating: 4.8,
    reviewCount: 2890,
    category: "Beauty",
    badge: "sale",
    description: "Brightening serum with 20% Vitamin C, hyaluronic acid, and niacinamide.",
  },
  {
    id: 8,
    name: "Mechanical Keyboard TKL",
    price: 119.00,
    image: "https://m.media-amazon.com/images/I/81bxzOcOR3L.jpg",
    rating: 4.6,
    reviewCount: 987,
    category: "Electronics",
    badge: "featured",
    description: "Tenkeyless layout with tactile switches, RGB backlight, and aluminum frame.",
  },
  {
    id: 9,
    name: "Linen Throw Blanket",
    price: 52.00,
    image: "https://m.media-amazon.com/images/I/71EUmwZhM6L.jpg",
    rating: 4.5,
    reviewCount: 345,
    category: "Home",
    description: "Lightweight stonewashed linen throw, perfect for all seasons.",
  },
  {
    id: 10,
    name: "Running Shoes Ultralight",
    price: 94.99,
    originalPrice: 119.99,
    image: "https://cdn.runrepeat.com/storage/gallery/buying_guide_primary/64/best-lightweight-running-shoes-001-22300149-main.jpg",
    rating: 4.7,
    reviewCount: 1678,
    category: "Sports",
    badge: "sale",
    description: "Breathable mesh upper with responsive foam midsole for long-distance runs.",
  },
  {
    id: 11,
    name: "Rose Gold Perfume",
    price: 68.00,
    image: "https://slimages.macysassets.com/is/image/MCY/products/0/optimized/19450420_fpx.tif?$filterlrg$&wid=327",
    rating: 4.6,
    reviewCount: 512,
    category: "Beauty",
    badge: "featured",
    description: "Floral-woody fragrance with notes of rose, sandalwood, and musk.",
  },
  {
    id: 12,
    name: "Bamboo Desk Organizer",
    price: 29.99,
    image: "https://m.media-amazon.com/images/I/71davshOLjL.jpg",
    rating: 4.4,
    reviewCount: 289,
    category: "Home",
    badge: "new",
    description: "Eco-friendly bamboo organizer with 6 compartments for a tidy workspace.",
  },
];
